application: mefingram
version: 1
runtime: python27
api_version: 1
threadsafe: false

skip_files:
- env
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^.*/solr/.*

builtins:
- remote_api: on
- appstats: on

handlers:
#- url: /static
#  static_dir: sirc/fe/static
#  expiration: "1m"

#- url: /remote_api
#  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#  login: optional

- url: /.*
  script: gae.app

